# Generated by Django 5.2 on 2025-04-15 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('campos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wiki', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion_campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=50)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.campo')),
            ],
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=50)),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.wiki')),
            ],
        ),
        migrations.AddField(
            model_name='campo',
            name='wiki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.wiki'),
        ),
    ]
