# Generated by Django 5.2 on 2025-04-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wiki",
            name="context",
            field=models.TextField(blank=True, null=True),
        ),
    ]
