# Generated by Django 5.2 on 2025-04-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_wiki_context"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wiki",
            name="context",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
